f=open("a.txt","w+")

f.write("ajay lohia\n")
f.write("ajay lohia\n")
f.flush()
f.write("ajay lohia\n")
f.write("ajay lohia\n")
f.flush()
f.write("ajay lohia\n")
f.write("ajay lohia\n")
f.flush()
f.write("ajay lohia\n")
f.write("ajay lohia\n")
f.close()